import {
  User,
  Institution,
  Department,
  Course,
  CourseUnit,
  Concept,
  Student,
  Assessment,
  AssessmentQuestion,
  Alert,
  InstitutionalReport,
  DataImportRecord,
  AuditLog,
  SimulationScenarioSettings,
  DigitalTwinNode,
  DigitalTwinEdge,
} from './types.ts';

export const SEED_INSTITUTION: Institution = {
  id: 'inst-01',
  name: 'National Polytechnic University',
  code: 'NPU',
  domain: 'npu.edu',
  type: 'University',
  studentCount: 1420,
  facultyCount: 148,
};

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: 'dept-cs',
    name: 'Computer Science',
    code: 'CS',
    institutionId: 'inst-01',
    headOfDepartment: 'Dr. Aris Thorne',
  },
  {
    id: 'dept-ee',
    name: 'Electrical Engineering',
    code: 'EE',
    institutionId: 'inst-01',
    headOfDepartment: 'Dr. Elena Rostova',
  },
  {
    id: 'dept-me',
    name: 'Mechanical Engineering',
    code: 'ME',
    institutionId: 'inst-01',
    headOfDepartment: 'Dr. Marcus Sterling',
  },
];

export const SEED_COURSES: Course[] = [
  {
    id: 'course-cs201',
    code: 'CS201',
    name: 'Data Structures',
    departmentId: 'dept-cs',
    departmentName: 'Computer Science',
    semester: 3,
    credits: 4,
    prerequisites: ['CS101'],
    riskLevel: 'MEDIUM',
    riskScore: 54,
    failureRate: 18.2,
    enrolledStudents: 310,
    status: 'Warning',
    description: 'Fundamental linear and hierarchical data structures, asymptotic algorithmic complexity, and abstract data types.',
    instructor: 'Prof. Ronald Chen',
  },
  {
    id: 'course-cs304',
    code: 'CS304',
    name: 'Database Systems',
    departmentId: 'dept-cs',
    departmentName: 'Computer Science',
    semester: 4,
    credits: 3,
    prerequisites: ['CS201'],
    riskLevel: 'LOW',
    riskScore: 28,
    failureRate: 7.4,
    enrolledStudents: 275,
    status: 'Healthy',
    description: 'Relational algebra, SQL, database normalization normal forms, indexing, ACID transactions, and query optimization.',
    instructor: 'Dr. Sarah Vance',
  },
  {
    id: 'course-cs305',
    code: 'CS305',
    name: 'Operating Systems',
    departmentId: 'dept-cs',
    departmentName: 'Computer Science',
    semester: 5,
    credits: 4,
    prerequisites: ['CS201'],
    riskLevel: 'HIGH',
    riskScore: 78,
    failureRate: 26.5,
    enrolledStudents: 240,
    status: 'Critical',
    description: 'Kernel architectures, concurrent processes, threads, synchronization primitives, virtual memory management, and paging.',
    instructor: 'Prof. Ronald Chen',
  },
  {
    id: 'course-math202',
    code: 'MATH202',
    name: 'Engineering Mathematics II',
    departmentId: 'dept-ee',
    departmentName: 'Electrical Engineering',
    semester: 3,
    credits: 4,
    prerequisites: ['MATH101'],
    riskLevel: 'HIGH',
    riskScore: 84,
    failureRate: 31.8,
    enrolledStudents: 380,
    status: 'Critical',
    description: 'Multivariable calculus, differential equations, Fourier transforms, Laplace domains, and linear differential systems.',
    instructor: 'Dr. Katherine Weber',
  },
  {
    id: 'course-cs308',
    code: 'CS308',
    name: 'Computer Networks',
    departmentId: 'dept-cs',
    departmentName: 'Computer Science',
    semester: 5,
    credits: 3,
    prerequisites: ['CS201'],
    riskLevel: 'MEDIUM',
    riskScore: 46,
    failureRate: 14.1,
    enrolledStudents: 220,
    status: 'Healthy',
    description: 'Layered OSI and TCP/IP stack, socket programming, packet routing protocols, congestion control, and transport layers.',
    instructor: 'Dr. Elena Rostova',
  },
  {
    id: 'course-cs401',
    code: 'CS401',
    name: 'Machine Learning',
    departmentId: 'dept-cs',
    departmentName: 'Computer Science',
    semester: 7,
    credits: 4,
    prerequisites: ['MATH202', 'CS201'],
    riskLevel: 'HIGH',
    riskScore: 72,
    failureRate: 23.4,
    enrolledStudents: 195,
    status: 'Critical',
    description: 'Supervised and unsupervised learning, empirical risk minimization, gradient descent, linear regression, and neural networks.',
    instructor: 'Dr. Aris Thorne',
  },
];

export const SEED_CONCEPTS: Concept[] = [
  {
    id: 'c-alg-manip',
    code: 'MTH-ALG',
    name: 'Algebraic Manipulation',
    courseId: 'course-math202',
    courseCode: 'MATH101',
    courseName: 'Engineering Mathematics I',
    masteryRate: 58.4,
    failureRate: 41.6,
    riskScore: 82,
    riskLevel: 'HIGH',
    affectedStudents: 210,
    prerequisiteIds: [],
    downstreamIds: ['c-diff', 'c-integ'],
    trend: 'increasing',
    description: 'Foundational factoring, exponent rules, and polynomial manipulation necessary for calculus transitions.',
  },
  {
    id: 'c-diff',
    code: 'MTH-DIF',
    name: 'Differentiation',
    courseId: 'course-math202',
    courseCode: 'MATH101',
    courseName: 'Engineering Mathematics I',
    masteryRate: 67.2,
    failureRate: 32.8,
    riskScore: 68,
    riskLevel: 'MEDIUM',
    affectedStudents: 165,
    prerequisiteIds: ['c-alg-manip'],
    downstreamIds: ['c-integ', 'c-regr'],
    trend: 'stable',
    description: 'Chain rule, implicit differentiation, and rate of change fundamentals.',
  },
  {
    id: 'c-integ',
    code: 'MTH-INT',
    name: 'Integration',
    courseId: 'course-math202',
    courseCode: 'MATH202',
    courseName: 'Engineering Mathematics II',
    masteryRate: 52.8,
    failureRate: 47.2,
    riskScore: 88,
    riskLevel: 'HIGH',
    affectedStudents: 235,
    prerequisiteIds: ['c-diff', 'c-alg-manip'],
    downstreamIds: ['c-diff-eq', 'c-prob'],
    trend: 'increasing',
    description: 'Integration by parts, substitution, and multivariable line integrals.',
  },
  {
    id: 'c-diff-eq',
    code: 'MTH-ODE',
    name: 'Differential Equations',
    courseId: 'course-math202',
    courseCode: 'MATH202',
    courseName: 'Engineering Mathematics II',
    masteryRate: 48.6,
    failureRate: 51.4,
    riskScore: 92,
    riskLevel: 'HIGH',
    affectedStudents: 260,
    prerequisiteIds: ['c-integ'],
    downstreamIds: ['c-regr', 'c-proc'],
    trend: 'increasing',
    description: 'First and second order ordinary differential equations, boundary value systems, and Laplace transforms.',
  },
  {
    id: 'c-prob',
    code: 'MTH-PRB',
    name: 'Probability & Statistics',
    courseId: 'course-math202',
    courseCode: 'MATH202',
    courseName: 'Engineering Mathematics II',
    masteryRate: 71.5,
    failureRate: 28.5,
    riskScore: 45,
    riskLevel: 'MEDIUM',
    affectedStudents: 110,
    prerequisiteIds: ['c-integ'],
    downstreamIds: ['c-regr'],
    trend: 'stable',
    description: 'Continuous random variables, probability density functions, and Bayes theorem.',
  },
  {
    id: 'c-arrays',
    code: 'CS-ARR',
    name: 'Arrays & Dynamic Pointers',
    courseId: 'course-cs201',
    courseCode: 'CS201',
    courseName: 'Data Structures',
    masteryRate: 79.4,
    failureRate: 20.6,
    riskScore: 32,
    riskLevel: 'LOW',
    affectedStudents: 64,
    prerequisiteIds: [],
    downstreamIds: ['c-trees', 'c-proc'],
    trend: 'stable',
    description: 'Contiguous memory layout, pointer arithmetic, dynamic memory allocation, and array bounds safety.',
  },
  {
    id: 'c-trees',
    code: 'CS-TRE',
    name: 'Trees & Heaps',
    courseId: 'course-cs201',
    courseCode: 'CS201',
    courseName: 'Data Structures',
    masteryRate: 64.0,
    failureRate: 36.0,
    riskScore: 61,
    riskLevel: 'MEDIUM',
    affectedStudents: 122,
    prerequisiteIds: ['c-arrays'],
    downstreamIds: ['c-graphs', 'c-sql'],
    trend: 'increasing',
    description: 'Binary search trees, balanced AVL rotations, red-black invariant properties, and binary min/max heaps.',
  },
  {
    id: 'c-graphs',
    code: 'CS-GRP',
    name: 'Graphs & Traversals',
    courseId: 'course-cs201',
    courseCode: 'CS201',
    courseName: 'Data Structures',
    masteryRate: 55.3,
    failureRate: 44.7,
    riskScore: 76,
    riskLevel: 'HIGH',
    affectedStudents: 158,
    prerequisiteIds: ['c-trees'],
    downstreamIds: ['c-routing'],
    trend: 'increasing',
    description: 'Adjacency lists, Dijkstra shortest path, BFS/DFS cycles, and topological sorting algorithms.',
  },
  {
    id: 'c-sql',
    code: 'DB-SQL',
    name: 'SQL & Relational Algebra',
    courseId: 'course-cs304',
    courseCode: 'CS304',
    courseName: 'Database Systems',
    masteryRate: 83.1,
    failureRate: 16.9,
    riskScore: 24,
    riskLevel: 'LOW',
    affectedStudents: 48,
    prerequisiteIds: ['c-trees'],
    downstreamIds: ['c-norm'],
    trend: 'decreasing',
    description: 'Declarative querying, projection, selection, nested subqueries, and grouping sets.',
  },
  {
    id: 'c-norm',
    code: 'DB-NRM',
    name: 'Normalization & Dependencies',
    courseId: 'course-cs304',
    courseCode: 'CS304',
    courseName: 'Database Systems',
    masteryRate: 74.5,
    failureRate: 25.5,
    riskScore: 42,
    riskLevel: 'MEDIUM',
    affectedStudents: 85,
    prerequisiteIds: ['c-sql'],
    downstreamIds: ['c-trans'],
    trend: 'stable',
    description: 'Functional dependencies, 1NF through BCNF decomposition, and lossless join verification.',
  },
  {
    id: 'c-trans',
    code: 'DB-TXN',
    name: 'Transactions & Concurrency',
    courseId: 'course-cs304',
    courseCode: 'CS304',
    courseName: 'Database Systems',
    masteryRate: 63.2,
    failureRate: 36.8,
    riskScore: 66,
    riskLevel: 'MEDIUM',
    affectedStudents: 108,
    prerequisiteIds: ['c-norm'],
    downstreamIds: ['c-threads'],
    trend: 'increasing',
    description: 'ACID guarantees, two-phase locking protocols, deadlock resolution, and isolation anomalies.',
  },
  {
    id: 'c-proc',
    code: 'OS-PRC',
    name: 'Processes & Virtual Memory',
    courseId: 'course-cs305',
    courseCode: 'CS305',
    courseName: 'Operating Systems',
    masteryRate: 59.8,
    failureRate: 40.2,
    riskScore: 74,
    riskLevel: 'HIGH',
    affectedStudents: 130,
    prerequisiteIds: ['c-arrays'],
    downstreamIds: ['c-threads'],
    trend: 'increasing',
    description: 'Address spaces, page tables, TLB caches, context switches, and CPU scheduler queues.',
  },
  {
    id: 'c-threads',
    code: 'OS-THR',
    name: 'Threads & Synchronization',
    courseId: 'course-cs305',
    courseCode: 'CS305',
    courseName: 'Operating Systems',
    masteryRate: 49.1,
    failureRate: 50.9,
    riskScore: 89,
    riskLevel: 'HIGH',
    affectedStudents: 162,
    prerequisiteIds: ['c-proc', 'c-trans'],
    downstreamIds: [],
    trend: 'increasing',
    description: 'Race conditions, mutexes, semaphores, monitor invariants, and reader-writer starvation.',
  },
  {
    id: 'c-tcp',
    code: 'NET-TCP',
    name: 'TCP/IP & Transport Protocols',
    courseId: 'course-cs308',
    courseCode: 'CS308',
    courseName: 'Computer Networks',
    masteryRate: 77.0,
    failureRate: 23.0,
    riskScore: 36,
    riskLevel: 'LOW',
    affectedStudents: 62,
    prerequisiteIds: [],
    downstreamIds: ['c-routing'],
    trend: 'stable',
    description: 'Three-way handshake, sequence acknowledgement, sliding window flow control, and slow-start congestion.',
  },
  {
    id: 'c-routing',
    code: 'NET-RTE',
    name: 'Routing & Packet Forwarding',
    courseId: 'course-cs308',
    courseCode: 'CS308',
    courseName: 'Computer Networks',
    masteryRate: 68.3,
    failureRate: 31.7,
    riskScore: 58,
    riskLevel: 'MEDIUM',
    affectedStudents: 88,
    prerequisiteIds: ['c-tcp', 'c-graphs'],
    downstreamIds: [],
    trend: 'stable',
    description: 'Link-state versus distance vector routing, autonomous systems, BGP border routing, and packet drop policies.',
  },
  {
    id: 'c-regr',
    code: 'ML-RGR',
    name: 'Regression & Optimization',
    courseId: 'course-cs401',
    courseCode: 'CS401',
    courseName: 'Machine Learning',
    masteryRate: 51.2,
    failureRate: 48.8,
    riskScore: 84,
    riskLevel: 'HIGH',
    affectedStudents: 145,
    prerequisiteIds: ['c-diff-eq', 'c-prob'],
    downstreamIds: [],
    trend: 'increasing',
    description: 'Cost surface convex hulls, multivariate gradient descent, L1/L2 ridge regularization, and learning rate schedules.',
  },
];

export const SEED_ASSESSMENTS: Assessment[] = [
  {
    id: 'asm-math202-mid',
    name: 'MATH202 Midterm Examination',
    courseId: 'course-math202',
    courseCode: 'MATH202',
    courseName: 'Engineering Mathematics II',
    date: '2026-03-12',
    maxMarks: 100,
    weightage: 35,
    difficulty: 'High',
    averageScore: 56.4,
    passingRate: 61.2,
    conceptIds: ['c-alg-manip', 'c-diff', 'c-integ', 'c-diff-eq'],
    anomaliesDetected: 4,
    questionCount: 8,
  },
  {
    id: 'asm-math202-q2',
    name: 'MATH202 Integration & ODE Quiz',
    courseId: 'course-math202',
    courseCode: 'MATH202',
    courseName: 'Engineering Mathematics II',
    date: '2026-02-24',
    maxMarks: 40,
    weightage: 15,
    difficulty: 'High',
    averageScore: 21.8,
    passingRate: 54.5,
    conceptIds: ['c-integ', 'c-diff-eq'],
    anomaliesDetected: 2,
    questionCount: 4,
  },
  {
    id: 'asm-cs305-mid',
    name: 'CS305 Concurrency & Memory Midterm',
    courseId: 'course-cs305',
    courseCode: 'CS305',
    courseName: 'Operating Systems',
    date: '2026-03-08',
    maxMarks: 100,
    weightage: 30,
    difficulty: 'High',
    averageScore: 59.2,
    passingRate: 64.0,
    conceptIds: ['c-proc', 'c-threads'],
    anomaliesDetected: 3,
    questionCount: 6,
  },
  {
    id: 'asm-cs201-mid',
    name: 'CS201 Trees & Graph Structures Midterm',
    courseId: 'course-cs201',
    courseCode: 'CS201',
    courseName: 'Data Structures',
    date: '2026-03-15',
    maxMarks: 100,
    weightage: 30,
    difficulty: 'Medium',
    averageScore: 68.7,
    passingRate: 78.4,
    conceptIds: ['c-arrays', 'c-trees', 'c-graphs'],
    anomaliesDetected: 1,
    questionCount: 7,
  },
  {
    id: 'asm-cs401-mid',
    name: 'CS401 Optimization & Empirical Risk Exam',
    courseId: 'course-cs401',
    courseCode: 'CS401',
    courseName: 'Machine Learning',
    date: '2026-03-18',
    maxMarks: 100,
    weightage: 35,
    difficulty: 'High',
    averageScore: 57.1,
    passingRate: 62.5,
    conceptIds: ['c-prob', 'c-regr'],
    anomaliesDetected: 3,
    questionCount: 6,
  },
  {
    id: 'asm-cs304-mid',
    name: 'CS304 Relational Design & Concurrency Exam',
    courseId: 'course-cs304',
    courseCode: 'CS304',
    courseName: 'Database Systems',
    date: '2026-03-05',
    maxMarks: 100,
    weightage: 30,
    difficulty: 'Low',
    averageScore: 76.9,
    passingRate: 88.0,
    conceptIds: ['c-sql', 'c-norm', 'c-trans'],
    anomaliesDetected: 0,
    questionCount: 6,
  },
];

export const SEED_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'q-m202-1',
    assessmentId: 'asm-math202-mid',
    questionNumber: 1,
    conceptId: 'c-alg-manip',
    conceptName: 'Algebraic Manipulation',
    maxMarks: 10,
    averageMarks: 4.8,
    difficultyIndex: 0.82,
    failureRate: 46.5,
  },
  {
    id: 'q-m202-2',
    assessmentId: 'asm-math202-mid',
    questionNumber: 2,
    conceptId: 'c-diff',
    conceptName: 'Differentiation',
    maxMarks: 10,
    averageMarks: 6.9,
    difficultyIndex: 0.54,
    failureRate: 28.0,
  },
  {
    id: 'q-m202-3',
    assessmentId: 'asm-math202-mid',
    questionNumber: 3,
    conceptId: 'c-integ',
    conceptName: 'Integration',
    maxMarks: 15,
    averageMarks: 7.2,
    difficultyIndex: 0.88,
    failureRate: 52.0,
  },
  {
    id: 'q-m202-4',
    assessmentId: 'asm-math202-mid',
    questionNumber: 4,
    conceptId: 'c-diff-eq',
    conceptName: 'Differential Equations',
    maxMarks: 20,
    averageMarks: 8.9,
    difficultyIndex: 0.94,
    failureRate: 58.5,
  },
  {
    id: 'q-os-1',
    assessmentId: 'asm-cs305-mid',
    questionNumber: 1,
    conceptId: 'c-proc',
    conceptName: 'Processes & Virtual Memory',
    maxMarks: 15,
    averageMarks: 9.1,
    difficultyIndex: 0.72,
    failureRate: 38.5,
  },
  {
    id: 'q-os-2',
    assessmentId: 'asm-cs305-mid',
    questionNumber: 2,
    conceptId: 'c-threads',
    conceptName: 'Threads & Synchronization',
    maxMarks: 25,
    averageMarks: 11.2,
    difficultyIndex: 0.91,
    failureRate: 56.2,
  },
];

export const SEED_ALERTS: Alert[] = [
  {
    id: 'alt-01',
    severity: 'HIGH',
    title: 'Critical Risk Propagation in Mathematics Dependency Chain',
    courseCode: 'MATH202',
    courseName: 'Engineering Mathematics II',
    conceptName: 'Integration Techniques',
    department: 'Electrical Engineering',
    date: '2026-03-22',
    description: 'A 28% drop in Integration mastery has propagated into Differential Equations and downstream Machine Learning (CS401), affecting 235 students.',
    status: 'UNACKNOWLEDGED',
    suggestedAction: 'Inject 2-week prerequisite remedial module on Integration Techniques prior to ODE evaluation.',
  },
  {
    id: 'alt-02',
    severity: 'HIGH',
    title: 'Severe Synchronization Failure Rate in Operating Systems Cohort',
    courseCode: 'CS305',
    courseName: 'Operating Systems',
    conceptName: 'Threads & Synchronization',
    department: 'Computer Science',
    date: '2026-03-20',
    description: 'Question 2 failure rate reached 56.2% on CS305 midterm due to concurrency primitives confusion originating in dynamic memory concepts.',
    status: 'UNACKNOWLEDGED',
    suggestedAction: 'Run forensic analysis on CS305 Midterm and review prerequisite lab scaffolding.',
  },
  {
    id: 'alt-03',
    severity: 'MEDIUM',
    title: 'Assessment Performance Declined Across 3 Consecutive Evaluations',
    courseCode: 'CS401',
    courseName: 'Machine Learning',
    conceptName: 'Regression & Optimization',
    department: 'Computer Science',
    date: '2026-03-19',
    description: 'Cohort average score dropped from 71.4% to 57.1% as continuous multivariate optimization topics commenced.',
    status: 'ACKNOWLEDGED',
    suggestedAction: 'Recalibrate assignment weighting and offer targeted vector calculus workshops.',
  },
  {
    id: 'alt-04',
    severity: 'LOW',
    title: 'Attendance Anomaly Signal in Computer Networks Cohort',
    courseCode: 'CS308',
    courseName: 'Computer Networks',
    conceptName: 'TCP/IP & Transport Protocols',
    department: 'Computer Science',
    date: '2026-03-14',
    description: 'Attendance in lecture section B slipped below 74% ahead of the sliding-window protocol laboratory.',
    status: 'RESOLVED',
    suggestedAction: 'Monitor attendance logs and sync lab submissions.',
  },
];

export const SEED_REPORTS: InstitutionalReport[] = [
  {
    id: 'rep-01',
    title: 'Institutional Academic Risk Forecast (Spring 2026)',
    type: 'Academic Risk Report',
    date: '2026-03-23',
    author: 'Institutional Analytics Division',
    department: 'Institution-Wide',
    executiveSummary: 'System-wide telemetry across 1,420 enrolled students indicates an aggregated predicted academic risk of 42.8%. Three critical bottleneck concepts account for 64% of downstream course distress.',
    keyFindings: [
      'Engineering Mathematics II (MATH202) exhibits the steepest risk gradient (+18% since midterm).',
      'Integration failure acts as the primary systemic driver for downstream failure in CS401 (Machine Learning) and MATH202 (Differential Equations).',
      'Operating Systems concurrency failure is strongly coupled with prerequisite weaknesses in dynamic memory pointers from CS201.',
    ],
    riskSignals: [
      'Prerequisite mastery decay: -28.4% across multivariable calculus topics.',
      'Midterm exam difficulty variance: +35.2% difficulty spike in ODE questions.',
      'Assignment submission decay: 18.1% drop in week 6 lab submissions.',
    ],
    rootCauses: [
      'Lack of foundational review in Algebraic Manipulation prior to multivariable integration.',
      'Insufficient hands-on thread synchronization practice before mid-semester evaluations.',
    ],
    affectedAreas: [
      'MATH202 (Engineering Mathematics II) - 235 students affected',
      'CS305 (Operating Systems) - 162 students affected',
      'CS401 (Machine Learning) - 145 students affected',
    ],
    recommendations: [
      'Mandate prerequisite diagnostic testing in week 1 of semester 3.',
      'Implement Counterfactual Scenario Alpha: Shift 10% weight from high-stakes midterms to weekly formative quizzes.',
      'Deploy the automated Learning Failure Forensics pipeline for any cohort with failure rates exceeding 25%.',
    ],
    modelInfo: 'Bayesian Causal Inference + Gradient-Boosted Risk Model v3.2. Deterministic calibration across 4 past academic cycles.',
  },
  {
    id: 'rep-02',
    title: 'Curriculum Bottleneck & Prerequisite Audit',
    type: 'Curriculum Bottleneck Report',
    date: '2026-03-21',
    author: 'Curriculum Governance Board',
    department: 'Computer Science & Mathematics',
    executiveSummary: 'Graph-based dependency analysis identified 2 severe structural bottlenecks in the Engineering and CS prerequisite networks that artificially throttle graduation throughput.',
    keyFindings: [
      'Algebraic Manipulation and Integration form a serial choke point in the curriculum graph.',
      'Relaxing concurrent enrollment for Database Systems while reinforcing Data Structures trees reduces total academic friction by 23%.',
    ],
    riskSignals: ['Downstream propagation index: 0.84 across technical minors.'],
    rootCauses: ['Asynchronous semester sequencing forcing students to take advanced coursework without fresh prerequisite recall.'],
    affectedAreas: ['Computer Science Dept', 'Electrical Engineering Dept'],
    recommendations: ['Resequence MATH202 to integrate modular review modules into syllabus.'],
    modelInfo: 'NetworkX Topological DAG Analysis & Eigenvector Centrality Scoring.',
  },
];

export const SEED_USERS: User[] = [
  {
    id: 'usr-super',
    name: 'Dr. Evelyn Vance',
    email: 'superadmin@demo.edu',
    role: 'SUPER_ADMIN',
    institutionId: 'inst-01',
    status: 'active',
    createdAt: '2025-01-10',
    lastLogin: '2026-09-24 09:42',
  },
  {
    id: 'usr-dean',
    name: 'Dean Mitchell Hayes',
    email: 'dean.mitchell@demo.edu',
    role: 'INSTITUTION_ADMIN',
    institutionId: 'inst-01',
    department: 'Computer Science',
    status: 'active',
    createdAt: '2025-02-14',
    lastLogin: '2026-09-24 08:30',
  },
  {
    id: 'usr-faculty',
    name: 'Prof. Ronald Chen',
    email: 'prof.chen@demo.edu',
    role: 'FACULTY',
    institutionId: 'inst-01',
    department: 'Computer Science',
    status: 'active',
    createdAt: '2025-03-01',
    lastLogin: '2026-09-23 16:15',
  },
  {
    id: 'usr-analyst',
    name: 'Turing Analyst Vance',
    email: 'analyst.turing@demo.edu',
    role: 'ANALYST',
    institutionId: 'inst-01',
    department: 'Institutional Intelligence',
    status: 'active',
    createdAt: '2025-03-10',
    lastLogin: '2026-09-24 07:50',
  },
];

export const SEED_IMPORTS: DataImportRecord[] = [
  {
    id: 'imp-01',
    datasetType: 'Assessment Results',
    fileName: 'spring_2026_midterm_scores.csv',
    rowsDetected: 4820,
    columnsDetected: 14,
    recordsImported: 4820,
    validationErrorsCount: 0,
    uploadedBy: 'dean.mitchell@demo.edu',
    uploadedAt: '2026-03-21 14:32',
    status: 'Completed',
  },
  {
    id: 'imp-02',
    datasetType: 'Student Performance',
    fileName: 'cohort_2024_cumulative_gpa.xlsx',
    rowsDetected: 1420,
    columnsDetected: 18,
    recordsImported: 1420,
    validationErrorsCount: 0,
    uploadedBy: 'analyst.turing@demo.edu',
    uploadedAt: '2026-03-18 10:15',
    status: 'Completed',
  },
  {
    id: 'imp-03',
    datasetType: 'Attendance',
    fileName: 'biweekly_rfid_attendance_w6.json',
    rowsDetected: 9640,
    columnsDetected: 8,
    recordsImported: 9640,
    validationErrorsCount: 0,
    uploadedBy: 'dean.mitchell@demo.edu',
    uploadedAt: '2026-03-15 09:00',
    status: 'Completed',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    user: 'Dr. Evelyn Vance (SUPER_ADMIN)',
    action: 'SIMULATION_EXECUTED',
    timestamp: '2026-09-24 02:40:12',
    resource: 'Simulator Scenario #Alpha-Intervention',
    details: 'Executed Monte Carlo counterfactual simulation on prerequisite bridging in MATH202.',
    ipAddress: '192.168.1.104',
  },
  {
    id: 'aud-02',
    user: 'Dean Mitchell Hayes (INSTITUTION_ADMIN)',
    action: 'FORENSIC_RUN',
    timestamp: '2026-09-23 21:15:40',
    resource: 'Forensic Pipeline CS305-MID',
    details: 'Initiated Bayesian causal DAG decomposition for Threads & Synchronization bottleneck.',
    ipAddress: '192.168.1.112',
  },
  {
    id: 'aud-03',
    user: 'Turing Analyst Vance (ANALYST)',
    action: 'REPORT_EXPORTED',
    timestamp: '2026-09-23 18:22:05',
    resource: 'Report rep-01 (PDF Export)',
    details: 'Generated institutional board executive briefing PDF for Spring 2026 Risk Forecast.',
    ipAddress: '192.168.1.98',
  },
  {
    id: 'aud-04',
    user: 'Prof. Ronald Chen (FACULTY)',
    action: 'DATA_INGESTED',
    timestamp: '2026-09-23 14:05:33',
    resource: 'Assessment Ingestion CS305',
    details: 'Uploaded 240 student question-level scores for CS305 Midterm evaluation.',
    ipAddress: '192.168.1.84',
  },
];

// Generator for 1,000+ realistic synthetic students
export function generateSyntheticStudents(): Student[] {
  const students: Student[] = [];
  const firstNames = [
    'Alexander', 'Amara', 'Benjamin', 'Chloe', 'Daniel', 'Fatima', 'Gabriel', 'Hannah',
    'Ishaan', 'Jessica', 'Kai', 'Liam', 'Maya', 'Noah', 'Olivia', 'Priya',
    'Quentin', 'Rohan', 'Sophia', 'Tariq', 'Uma', 'Victor', 'Wendy', 'Xavier',
    'Yasmin', 'Zachary', 'Aiden', 'Elena', 'Lucas', 'Nadia', 'Marcus', 'Aria',
    'Leo', 'Zoe', 'Julian', 'Layla', 'Adrian', 'Samira', 'Caleb', 'Nia'
  ];
  const lastNames = [
    'Patel', 'Kowalski', 'Chen', 'Okonkwo', 'Nakamura', 'Gupta', 'Silva', 'Mendoza',
    'Kim', 'Johansson', 'Ahmed', 'Dubois', 'Morales', 'Zhang', 'Russo', 'Al-Mansoor',
    'Schmidt', 'Becker', 'Venkatesh', 'Larsson', 'O\'Connor', 'Tanaka', 'Ibrahim', 'Novak',
    'Santos', 'Fischer', 'Yamamoto', 'Bhat', 'Moreau', 'Haddad', 'Kovacs', 'Gomez'
  ];
  const depts = ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering'];

  for (let i = 1; i <= 1050; i++) {
    const fName = firstNames[(i * 7 + 3) % firstNames.length];
    const lName = lastNames[(i * 11 + 5) % lastNames.length];
    const dept = depts[i % 3];
    const sem = ((i % 6) + 1) <= 6 ? ((i % 6) + 1) : 3;

    // Generate realistic seeded variance
    const baseScore = 45 + ((i * 37) % 52); // 45 to 97
    const gpa = Math.round(((baseScore / 100) * 2.5 + 1.5) * 100) / 100;
    const attendance = Math.min(99, Math.max(62, Math.round(baseScore + ((i % 13) - 6))));

    let riskLevel: 'HIGH' | 'MEDIUM' | 'LOW' = 'LOW';
    let riskScore = 15 + ((100 - baseScore) * 0.8);
    riskScore = Math.min(95, Math.max(12, Math.round(riskScore)));

    if (riskScore >= 70 || attendance < 72 || gpa < 2.5) {
      riskLevel = 'HIGH';
    } else if (riskScore >= 45 || attendance < 80 || gpa < 3.0) {
      riskLevel = 'MEDIUM';
    }

    const status = riskLevel === 'HIGH' ? 'Critical Intervention' : riskLevel === 'MEDIUM' ? 'Academic Warning' : 'Good Standing';

    const weaknesses: string[] = [];
    if (riskLevel === 'HIGH') {
      if (i % 2 === 0) weaknesses.push('Integration', 'Differential Equations');
      if (i % 3 === 0) weaknesses.push('Threads & Synchronization');
      if (weaknesses.length === 0) weaknesses.push('Algebraic Manipulation', 'Graphs & Traversals');
    } else if (riskLevel === 'MEDIUM') {
      if (i % 2 === 0) weaknesses.push('Trees & Heaps');
      else weaknesses.push('Normalization & Dependencies');
    }

    students.push({
      id: `stu-${i.toString().padStart(4, '0')}`,
      studentId: `NPU-2024-${(1000 + i).toString()}`,
      name: `${fName} ${lName}`,
      email: `${fName.toLowerCase()}.${lName.toLowerCase()}@student.npu.edu`,
      department: dept,
      semester: sem,
      gpa,
      attendanceRate: attendance,
      riskLevel,
      riskScore,
      status,
      enrollments: [
        {
          courseId: 'course-cs201',
          courseCode: 'CS201',
          courseName: 'Data Structures',
          midtermScore: Math.round(baseScore * 0.95),
          quizScore: Math.round(baseScore * 0.98),
          assignmentScore: Math.round(baseScore * 1.02),
          finalPredictedScore: Math.round(baseScore * 0.96),
          riskLevel: riskLevel === 'HIGH' ? 'HIGH' : 'LOW',
        },
        {
          courseId: 'course-math202',
          courseCode: 'MATH202',
          courseName: 'Engineering Mathematics II',
          midtermScore: Math.round(baseScore * 0.82),
          quizScore: Math.round(baseScore * 0.85),
          assignmentScore: Math.round(baseScore * 0.90),
          finalPredictedScore: Math.round(baseScore * 0.84),
          riskLevel: riskLevel,
        },
        {
          courseId: 'course-cs305',
          courseCode: 'CS305',
          courseName: 'Operating Systems',
          midtermScore: Math.round(baseScore * 0.88),
          quizScore: Math.round(baseScore * 0.92),
          assignmentScore: Math.round(baseScore * 0.94),
          finalPredictedScore: Math.round(baseScore * 0.87),
          riskLevel: riskScore > 60 ? 'HIGH' : 'MEDIUM',
        },
      ],
      conceptWeaknesses: weaknesses,
      attendanceHistory: [
        { week: 1, rate: Math.min(100, attendance + 4) },
        { week: 2, rate: Math.min(100, attendance + 2) },
        { week: 3, rate: attendance },
        { week: 4, rate: Math.max(50, attendance - 3) },
        { week: 5, rate: Math.max(50, attendance - 5) },
        { week: 6, rate: attendance },
      ],
      riskTimeline: [
        { month: 'Nov 2025', score: Math.max(10, riskScore - 12) },
        { month: 'Dec 2025', score: Math.max(10, riskScore - 8) },
        { month: 'Jan 2026', score: Math.max(10, riskScore - 4) },
        { month: 'Feb 2026', score: riskScore },
        { month: 'Mar 2026', score: Math.min(100, riskScore + 3) },
      ],
    });
  }

  return students;
}

export const SEED_STUDENTS = generateSyntheticStudents();
