import React from 'react';
import { Sparkles, Info } from 'lucide-react';

interface ChartCardProps {
  title: string;
  subtitle?: string;
  badge?: React.ReactNode;
  actions?: React.ReactNode;
  children: React.ReactNode;
  className?: string;
}

export const ChartCard: React.FC<ChartCardProps> = ({
  title,
  subtitle,
  badge,
  actions,
  children,
  className = '',
}) => {
  return (
    <div className={`bg-white rounded-xl border border-slate-200/80 p-5 shadow-xs ${className}`}>
      <div className="flex items-start justify-between gap-4 mb-4">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="text-sm font-semibold text-slate-900 tracking-tight">{title}</h3>
            {badge}
          </div>
          {subtitle && <p className="text-xs text-slate-500 mt-0.5">{subtitle}</p>}
        </div>
        {actions && <div className="flex items-center gap-2">{actions}</div>}
      </div>
      <div>{children}</div>
    </div>
  );
};

interface InsightPanelProps {
  title?: string;
  content: string;
  modelAttribution?: string;
  isLoading?: boolean;
  onRefresh?: () => void;
}

export const InsightPanel: React.FC<InsightPanelProps> = ({
  title = 'System Intelligence',
  content,
  modelAttribution = 'Grounded analytical synthesis generated by EDUFORENSICS causal reasoning pipeline. Model evaluation output.',
  isLoading,
  onRefresh,
}) => {
  return (
    <div className="bg-slate-900 text-white rounded-xl p-5 border border-slate-800 shadow-sm relative overflow-hidden">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-md bg-red-600/20 border border-red-500/30 flex items-center justify-center text-red-400">
            <Sparkles className="w-3.5 h-3.5" />
          </div>
          <span className="text-xs font-semibold uppercase tracking-wider text-slate-300">
            {title}
          </span>
        </div>
        {onRefresh && (
          <button
            onClick={onRefresh}
            disabled={isLoading}
            className="text-xs text-slate-400 hover:text-white transition-colors cursor-pointer"
          >
            {isLoading ? 'Synthesizing...' : 'Re-synthesize'}
          </button>
        )}
      </div>

      <p className="text-sm text-slate-200 leading-relaxed font-normal">
        {isLoading ? (
          <span className="inline-block animate-pulse text-slate-400">
            Running Bayesian propagation models...
          </span>
        ) : (
          content
        )}
      </p>

      <div className="mt-3 pt-3 border-t border-slate-800/80 flex items-center gap-1.5 text-xs text-slate-400 font-mono">
        <Info className="w-3 h-3 text-slate-400 shrink-0" />
        <span className="truncate">{modelAttribution}</span>
      </div>
    </div>
  );
};
